#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-package-information
Version  : 0.2.4
Release  : 8
URL      : https://files.pythonhosted.org/packages/5b/97/cb6282b146b645d9435d00e2502c3a3d7e5daecdba86b5bc989654dd1099/colcon-package-information-0.2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/5b/97/cb6282b146b645d9435d00e2502c3a3d7e5daecdba86b5bc989654dd1099/colcon-package-information-0.2.4.tar.gz
Summary  : Extension for colcon to output package information.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-package-information-python = %{version}-%{release}
Requires: colcon-package-information-python3 = %{version}-%{release}
Requires: colcon-core
BuildRequires : buildreq-distutils3
BuildRequires : colcon-core

%description
colcon-package-information
==========================
An extension for `colcon-core <https://github.com/colcon/colcon-core>`_ to provide information about the packages.

%package python
Summary: python components for the colcon-package-information package.
Group: Default
Requires: colcon-package-information-python3 = %{version}-%{release}

%description python
python components for the colcon-package-information package.


%package python3
Summary: python3 components for the colcon-package-information package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-package-information package.


%prep
%setup -q -n colcon-package-information-0.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571152259
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
